### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by Miskerest** [foreshadow/atom-python-run#2]
Steps to reproduce:

1. Installed python on work computer (Win7), without admin rights. However, python is still in PATH.
2. Attempting to run yields the following error.
3. The command I used to install python is:
    
    `msiexec /a python-2.7.12.msi /qb TARGETDIR=C:\Misker\python`

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-python-run](https://github.com/foreshadow/atom-python-run) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\mhb1115\.atom\packages\atom-python-run\lib\atom-python-run.js:13

TypeError: Cannot read property 'path' of null
    at atom-text-editor.run (C:\Users\mhb1115\.atom\packages\atom-python-run\lib\atom-python-run.js:13:64)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\mhb1115\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  6x -2:17.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:42.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:42.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41.1.0 grammar-selector:show (atom-text-editor.editor)
     -0:38.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 atom-python-run:run (atom-text-editor.editor)
     -0:17.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 Python run: run (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-python-run, v0.2.0

# Dev
No dev packages
```

**Comment by foreshadow** [comment]
I cannot figure out why.

**Comment by foreshadow** [comment]
When I hit F5 in editor that opened a new file (never saved), this error will occurs.
I will try to fix it in later version.

**Comment by foreshadow** [comment]
In the latest version, it will immediately save the file in current editor after `atom-python-run: run` is called.
If the file is created but never saved in atom, it will create and save the file in operation system as atom's API save() does.
I believe this is not happening again.
