### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, open '~/Dropbox\Programing\towers_of_hanoi.py'

### ISSUE THREAD

**Issue by mdpmcc** [foreshadow/atom-python-run#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-python-run](https://github.com/foreshadow/atom-python-run) package 0.7.3

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, open 'C:\Users\mdpmc\Dropbox\Programing\towers_of_hanoi.py'

```
At C:\Users\mdpmc\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1076

Error: UNKNOWN: unknown error, open 'C:\Users\mdpmc\Dropbox\Programing\towers_of_hanoi.py'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at File.module.exports.File.writeFileSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:19)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:915:26)
    at run (/packages/atom-python-run/lib/atom-python-run.js:67:12)
    at /packages/atom-python-run/lib/atom-python-run.js:49:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:53.5.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:29.4.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -4:19.4.0 core:confirm (input.hidden-input)
     -0:28 intentions:highlight (input.hidden-input)
     -0:27.6.0 core:paste (input.hidden-input)
     -0:24.4.0 core:backspace (input.hidden-input)
     -0:22.7.0 intentions:highlight (input.hidden-input)
     -0:22.3.0 core:save (input.hidden-input)
     -0:21.1.0 Python run: run-f5 (input.hidden-input)
```

### Non-Core Packages

```
atom-monokai 0.10.9 
atom-python-run 0.7.3 
autoclose-html 0.23.0 
autocomplete-python 1.8.62 
busy-signal 1.3.0 
highlight-selected 0.12.0 
intentions 1.1.2 
linter 2.1.0 
linter-ui-default 1.2.1 
minimap 4.26.8 
monokai 0.22.0 
pigments 0.39.1 
seti-ui 1.7.0 
```

**Comment by foreshadow** [comment]
Unknown error to me. Is there a symlink in your dropbox folder?

**Comment by mdpmcc** [comment]
Nope there are none in that dropbox folder

**Comment by xovertheyearsx** [comment]
how did you produce this output?

**Comment by foreshadow** [comment]
Version iterates, and this issue is too old.
