### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/tmp/mozilla_carreira0/plot_digits_classificatio...

### ISSUE THREAD

**Issue by VictorCarreira** [foreshadow/atom-python-run#27]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-python-run](https://github.com/foreshadow/atom-python-run) package 0.7.3

### Stack Trace

Uncaught Error: EACCES: permission denied, open '/tmp/mozilla_carreira0/plot_digits_classification.py'

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1076

Error: EACCES: permission denied, open '/tmp/mozilla_carreira0/plot_digits_classification.py'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at File.module.exports.File.writeFileSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:19)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:915:26)
    at run (/packages/atom-python-run/lib/atom-python-run.js:67:12)
    at /packages/atom-python-run/lib/atom-python-run.js:49:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:42.3.0 core:confirm (input.hidden-input)
  2x -2:34.8.0 core:backspace (input.hidden-input)
     -2:31.4.0 core:confirm (input.hidden-input)
     -0:06.9.0 Python run: run-f5 (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
autocomplete-fortran 0.9.4 
autocomplete-python 1.8.63 
dark-bint-syntax 0.10.0 
Hydrogen 1.10.1 
language-fortran 2.1.0 
language-matlab 0.2.1 
latex 0.43.0 
latexer 0.3.0 
latextools 0.8.5 
script 3.14.1 
terminal-fusion 2.4.4 
```

**Comment by xovertheyearsx** [comment]
This isn't reproducible with the information you've given.

**Comment by foreshadow** [comment]
Version iterates, and this issue is too old.
