### ISSUE TITLE
Uncaught Error: Can't save a buffer with no file

### ISSUE THREAD

**Issue by RISHUROCKS** [foreshadow/atom-python-run#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-python-run](https://github.com/foreshadow/atom-python-run) package 0.9.4

### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At C:\Users\Rishab\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1267

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1267:21)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1251:25)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:1018:32)
    at Object.saveAndRun (/packages/atom-python-run/lib/atom-python-run.js:18:50)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -0:53.7.0 core:backspace (input.hidden-input)
     -0:30.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:27.7.0 editor:newline (input.hidden-input)
     -0:24.2.0 Python run: run-f5 (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.4 
autocomplete-python 1.10.3 
```

**Comment by Chinnguy** [comment]
Make sure you have saved the script you are working on. Once you have it saved, the error should go away.

**Comment by xovertheyearsx** [comment]
We could apply a simple `try catch` statement and we could notify the use that they have to create a file before attempting to save the buffer.

v0.9.4 atom-python-run.js:lines 16-24 look like this right now for handling the buffer
```javascript
function saveAndRun(key) {
    console.log(`${key} pressed`)
    atom.workspace.getActiveTextEditor().save().then(() => {
        run({
            'command': atom.config.get(`atom-python-run.${key}Command`),
            'pause': atom.config.get(`atom-python-run.${key}Pause`),
        });
    });
}
```

We could do something like this,
```javascript
function saveAndRun(key) {
    try {
        console.log(`${key} pressed`)
        atom.workspace.getActiveTextEditor().save().then(() => {
            run({
                'command': atom.config.get(`atom-python-run.${key}Command`),
                'pause': atom.config.get(`atom-python-run.${key}Pause`),
            });
        });
    } catch(e) {
        atom.notifications.addError(`atom-python-run: \`BufferException\`: \`Can't save a buffer with no file\`: You failed to create the file before attempting to execute it. You must create the file first and then execute it after it has been created.`);
        return;
    }
}
```

**Comment by RISHUROCKS** [comment]
thank you guys...
