### ISSUE TITLE
Getting an error while installing you package using Atom.

### ISSUE THREAD

**Issue by kotharan** [foreshadow/atom-python-run#88]
I tried intsalling it varios times but it results in the same error. 

![error](https://user-images.githubusercontent.com/26471560/43159511-62538cb2-8f37-11e8-8cba-405f7ce23f62.PNG)

In case the photo isn't visible, the error goes like : 

fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EPERM: operation not permitted, mkdir 'C:\PROGRA~1\Java\JDK18~1.0_1\bin\d-118624-8948-f5tgww.gqmyhqia4i'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.mkdirSync (C:\Users\DELL\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\temp\lib\temp.js:137:6)
    at Request.<anonymous> (C:\Users\DELL\AppData\Local\atom\app-1.28.2\resources\app\apm\lib\install.js:335:41)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (C:\Users\DELL\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\request\request.js:1062:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)

Thanks for your help.

**Comment by kotharan** [comment]
Hello you there?

**Comment by xovertheyearsx** [comment]
You can out put a list of other installed packages (that way we can see if one is conflicting with this one for [example](https://github.com/foreshadow/atom-python-run/wiki/00-Readme#windows)) by using apm (atom package manager cli tool).

`$ apm list --installed`

and you can just copy and paste the contents there. This may be an issue with atom or with the package. My best guess is it may be Atom and/or a conflicting package seeing as the error seems to be occurring within a package dependency `fs.js` _on line 922_.

Sometimes you have to rebuild the module cache which apm can do for you.

`$ apm rebuild-module-cache`

Sometimes certain JS pacakges need to be recompiled and reconfigured for one reason or another and this can fix that issue. Other than that, I really don't know without more info.

You can check out these links and hopefully they lead to something useful.

* [Wiki - readme](https://github.com/foreshadow/atom-python-run/wiki/00-Readme#readme)
* [Logs - console log](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#console-log)
* [Logs - cp log](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#cp-log)
* [How to use atom-python-run](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#how-do-i-use-atom-python-run)

You may also want to check out these [alternative resources](https://github.com/foreshadow/atom-python-run/wiki/03-Resources) and check out atom.io forums and see if others have faced a similar issue. With some web searching and patience, you find that it might be something else entirely thats keeping you from installing the package.
