### ISSUE TITLE
Failed to load the atom-python-run package

### ISSUE THREAD

**Issue by snuweb** [foreshadow/atom-python-run#99]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-python-run](https://github.com/foreshadow/atom-python-run) package 0.9.7

### Stack Trace

Failed to load the atom-python-run package

```
At Unexpected token a in JSON at position 1

SyntaxError: Unexpected token a in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseObject (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/season/lib/cson.js:58:25)
    at parseContentsSync (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/season/lib/cson.js:72:22)
    at Object.readFileSync (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/season/lib/cson.js:184:20)
    at keymaps.getKeymapPaths.map (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:454:20)
    at Array.map (<anonymous>)
    at Package.loadKeymaps (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:452:50)
    at measure (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:133:20)
    at Package.measure (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:619:16)
    at config.transact (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:532:20)
    at Config.transact (~/AppData/Local/atom/app-1.31.1/resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:530:23)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.31.1/resources/app/src/atom-environment.js:837:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
atom-runner 2.7.1 
atom-terminal 0.8.0 
autocomplete-python 1.10.12 
file-icons 2.1.25 
highlight-selected 0.14.0 
Hydrogen 2.6.0 
linter 2.2.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.8.4 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.18.1 
script-runner 2.3.1 
```

**Comment by snuweb** [comment]
does any one saw this issue?
